apiVersion: v1
kind: Service
metadata:
  name: omni-db
  labels:
    app: omni-db
spec:
  ports:
    - port: 5432
  selector:
    app: omni-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: omni-db
spec:
  serviceName: "omni-db"
  replicas: 1
  selector:
    matchLabels:
      app: omni-db
  template:
    metadata:
      labels:
        app: omni-db
    spec:
      containers:
      - name: postgis
        image: postgis/postgis:15-3.3
        env:
        - name: POSTGRES_USER
          value: "monish_admin"
        - name: POSTGRES_PASSWORD
          value: "omnipath_password"
        - name: POSTGRES_DB
          value: "football_analytics"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
